In [42]:
import pandas as pd

datafile='./data/air_data.csv'

result='explore.xlsx'

data=pd.read_csv(datafile,encoding='utf-8')
data.head()

explore=data.describe(percentiles=[],include='all').T
print(explore)

explore1=explore[['null','max','min']]
explore.column=[u'空值数',u'最大值',u'最小值']

explore.to_excel(result)

                           count unique         top   freq          mean  \
MEMBER_NO                62988.0    NaN         NaN    NaN       31494.5   
FFP_DATE                   62988   3068  2011/01/13    184           NaN   
FIRST_FLIGHT_DATE          62988   3406  2013/02/16     96           NaN   
GENDER                     62985      2           男  48134           NaN   
FFP_TIER                 62988.0    NaN         NaN    NaN      4.102162   
WORK_CITY                  60719   3310          广州   9385           NaN   
WORK_PROVINCE              59740   1185          广东  17507           NaN   
WORK_COUNTRY               62962    118          CN  57748           NaN   
AGE                      62568.0    NaN         NaN    NaN     42.476346   
LOAD_TIME                  62988      1  2014/03/31  62988           NaN   
FLIGHT_COUNT             62988.0    NaN         NaN    NaN     11.839414   
BP_SUM                   62988.0    NaN         NaN    NaN  10925.081254   
EP_SUM_YR_1 

KeyError: "['null'] not in index"

In [43]:
from __future__ import division
from pandas import DataFrame,Series
import pandas as pd

datafile='./data/air_data.csv'
data=pd.read_csv(datafile,encoding='utf-8')

cleanedfile='cleaned.xlsx'

data1=data[data['SUM_YR_1'].notnull()*data['SUM_YR_2'].notnull()]

index1=data1['SUM_YR_1']!=0
index2=data1['SUM_YR_2']!=0
index3=(data1['SEG_KM_SUM']==0)&(data1['avg_discount']==0)
data1=data1[index1|index2|index3]

data1.to_excel(cleanedfile)
data2=data1[['LOAD_TIME','FFP_DATE','LAST_TO_END','FLIGHT_COUNT','SEG_KM_SUM','avg_discount']]
data2.to_excel('datadecrese.xlsx')

In [44]:
import numpy as np
data=pd.read_excel('./datadecrese.xlsx')

data['L1']=pd.to_datetime(data['LOAD_TIME'])-pd.to_datetime(data["FFP_DATE"])
print(data['L1'].head())

data['L3']=data['L1']/np.timedelta64(1,'M')
print(data['L3'].head())

0   2706 days
1   2597 days
2   2615 days
3   2047 days
4   1816 days
Name: L1, dtype: timedelta64[ns]
0    88.905316
1    85.324134
2    85.915522
3    67.253948
4    59.664469
Name: L3, dtype: float64


In [45]:
print(data['L1'].head())

0   2706 days
1   2597 days
2   2615 days
3   2047 days
4   1816 days
Name: L1, dtype: timedelta64[ns]


In [46]:
data["L3"]=data["L3"].round(2)
data['LAST_TO_END']=(data['LAST_TO_END']/30).round(2)
data['avg_discount']=data['avg_discount'].round(2)

data.drop('L1',axis=1,inplace=True)
data.drop(data.columns[:3],axis=1,inplace=True)

In [47]:

print(data.head())
data=data.rename(columns={'LAST_TO_END':'R','FLIGHT_COUNT':'F',
                     'SEG_KM_SUM':'M','avg_discount':'C','L3':'L'})

   LAST_TO_END  FLIGHT_COUNT  SEG_KM_SUM  avg_discount     L3
0         0.03           210      580717          0.96  88.91
1         0.23           140      293678          1.25  85.32
2         0.37           135      283712          1.25  85.92
3         3.23            23      281336          1.09  67.25
4         0.17           152      309928          0.97  59.66


In [48]:
print(data.head())

      R    F       M     C      L
0  0.03  210  580717  0.96  88.91
1  0.23  140  293678  1.25  85.32
2  0.37  135  283712  1.25  85.92
3  3.23   23  281336  1.09  67.25
4  0.17  152  309928  0.97  59.66


In [51]:
data.to_excel('./sxgz.xlsx',index=False)

def f(x):
    return Series([x.min(),x.max()],index=['min','max'])
d=data.apply(f)
d.to_excel('./summary_data.xlsx')

In [53]:
d1=pd.read_excel('./sxgz.xlsx')
d1=d1.astype('float64')
d2=(d1-d1.mean())/d1.std()
d1=d2.iloc[:,[4,0,1,2,3]]
d1.columns=['Z'+i for i in d1.columns]
d1.to_excel('./sjbzh.xlsx',index=False)

In [1]:
import pandas as pd
from pandas import DataFrame,Series
from sklearn.cluster import KMeans
# k=5
k=4
d3=pd.read_excel('sjbzh.xlsx')

kmodel=KMeans(n_clusters=k)
kmodel.fit(d3)

labels=kmodel.labels_
demo=DataFrame(labels,columns=['numbers'])
demo1=DataFrame(kmodel.cluster_centers_,columns=d3.columns)
demo2=demo['numbers'].value_counts()

demo4=pd.concat([demo2,demo1],axis=1)
demo4.index.name='labels'
demo4.to_excel('kmeans_results.xlsx')


/Users/yingmanji/opt/miniconda3/envs/d2l/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [2]:
demo2=demo['numbers'].value_counts()
demo2

1    26288
0    17246
3    12930
2     5580
Name: numbers, dtype: int64

In [3]:
print(kmodel.cluster_centers_)
print(kmodel.labels_)

[[ 1.14008975 -0.36387755 -0.0991142  -0.10785958  0.0943045 ]
 [-0.69557799 -0.40926871 -0.16932728 -0.16943478 -0.13156925]
 [ 0.47989632 -0.79606384  2.43136981  2.37531725  0.38133682]
 [-0.31192791  1.6588751  -0.57193322 -0.53591403 -0.02266018]]
[2 2 2 ... 1 3 3]
